[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT"

[workspace.dependencies]
anyhow = "1.0"
arboard = "3.3"
clap = { version = "4.4", features = ["derive"] }
