#!/usr/bin/env bash
# Shows the contents of an executable found in your PATH using cat or bat.
# Usage: catbin <command-name>

set -e
set -u

if [[ $# != 1 ]]; then
  echo 'usage: echobin something_in_your_path' >&2
  exit 1
fi

if hash bat 2>/dev/null; then
  cat_command=bat
else
  # shellcheck disable=SC2209
  cat_command=cat
fi

exec "$cat_command" "$(command -v "$1")"