#!/usr/bin/env bash
# Creates a temporary file path, prints it, and copies it to the clipboard.
# Usage: cptmp

set -e
set -u
set -o pipefail

path="$(mktemp | tr -d '\n')"
echo -n "$path"
echo -n "$path" | copy