#!/usr/bin/env bash
# Opens DuckDuckGo in the browser, optionally searching for the provided terms.
# Usage: duck [search terms...]

set -e
set -u
set -o pipefail

BROWSER="${BROWSER:-open}"

if [ $# -eq 0 ]; then
  "$BROWSER" 'https://duckduckgo.com'
else
  args="$*"
  search="${args// /+}"
  "$BROWSER" "https://duckduckgo.com/?q=$search"
fi