#!/usr/bin/env bash
# Flushes the local DNS cache on supported systems (currently macOS).
# Usage: flushdns

set -e
set -u

if [[ "$(uname)" == 'Darwin' ]]; then
  sudo dscacheutil -flushcache
  sudo killall -HUP mDNSResponder
else
  echo 'not supported yet'
fi