#!/usr/bin/env bash
# Uses fzf to interactively select and check out a git branch.
# Usage: git-fzf-checkout

set -e
set -u
set -o pipefail

branches="$(git branch)"
branch="$(echo "$branches" | fzf +m --height=1%)"
git checkout "$(echo "$branch" | awk '{print $1}' | sed "s/.* //")"