#!/usr/bin/env bash
# Runs ls -a with color flags appropriate for the current platform.
# Usage: la [ls-args...]

set -e
set -u

if [[ "$(uname -s)" == 'Darwin' ]]; then
  flag='-G'
else
  flag='--color'
fi

ls -a "$flag" "$@"