#!/usr/bin/env bash
# Merges multiple PDFs into a single file using Ghostscript.
# Usage: mergepdfs <output.pdf> <input.pdf...>

set -e
set -u

output_file="$1"
shift

gs -q -dNOPAUSE -dBATCH -sDEVICE=pdfwrite -sOutputFile="$output_file" "$@"