#!/usr/bin/env bash
# Updates package.json devDependencies to their latest versions.
# Usage: npm-update-dev-dependencies

set -e
set -u
set -o pipefail

deps="$(node -p 'Object.keys(require("./package.json").devDependencies).map(d => d + "@latest").join(" ")')"
npm install --save-dev $deps