#!/usr/bin/env bash
# Updates package.json dependencies to their latest versions.
# Usage: npm-update-dependencies

set -e
set -u
set -o pipefail

deps="$(node -p 'Object.keys(require("./package.json").dependencies).map(d => d + "@latest").join(" ")')"
npm install --save $deps