#!/usr/bin/env bash
# Repackages an npm tarball with optimal gzip compression for size comparison.
# Usage: npm-repack <package-name-or-directory>

set -e
set -u
set -o pipefail

npm pack "$1"

du -b "$1"*.tgz

gunzip "$1"*.tgz

zopfli --gzip -i1000 "$1"*.tar

du -b "$1"*.tar.gz