#!/usr/bin/env bash
# Generates a random numeric PIN of the requested length.
# Usage: pingen [length]

set -e
set -u
set -o pipefail

shuf --random-source=/dev/urandom -i 0-9 -r -n "${1:-6}" | paste -sd ''