#!/usr/bin/env bash
# Displays images in mpv, looping each frame indefinitely.
# Usage: pix <image-files...>

set -e
set -u
set -o pipefail

exec mpv \
  --image-display-duration=inf \
  --loop-file=inf \
  "$@"