#!/usr/bin/env bash
# Shows the current time and today's calendar with the current date highlighted.
# Usage: rn

set -e
set -u

date "+%l:%M%p on %A, %B %e, %Y"
echo
cal | grep -E "\b$(date '+%e')\b| "