#!/usr/bin/env bash
# Opens a temporary file in $EDITOR for quick notes, deleting it afterward manually if desired.
# Usage: scratch

set -e
set -u
set -o pipefail

file="$(mktemp)"
echo "Editing $file"
exec "$EDITOR" "$file"