#!/usr/bin/env bash
# Puts the computer to sleep using macOS or Linux commands.
# Usage: sleepybear

set -e
set -u

if [[ "$(uname)" == 'Darwin' ]]; then
  exec /usr/bin/osascript -e 'tell application "System Events" to sleep'
else
  systemctl suspend
fi