#!/usr/bin/env bash
# Measures elapsed time by timing stdin until EOF.
# Usage: stopwatch

set -e
set -u

date "+%l:%M:%S%p: stopwatch started (^D to stop)"
time cat
date "+%l:%M:%S%p: stopwatch stopped"