#!/usr/bin/env bash
# Converts curly quotes in the input to straight ASCII quotes.
# Usage: straightquote < input

set -e
set -u
set -o pipefail

# shellcheck disable=SC1112
sed 's/[“”]/"/g; s/[‘’]/'"'"'/g'