#!/usr/bin/env bash
# Plays video in the terminal using mpv's tct video output.
# Usage: tuivid <video-path>

set -e
set -u
set -o pipefail

exec mpv --quiet --vo=tct --vo-tct-256=yes --vo-tct-algo=plain --framedrop=vo "$@"