#!/usr/bin/env bash
# Opens the target file in read-only mode using the configured editor.
# Usage: view <file>

set -e
set -u
set -o pipefail

if [[ "$EDITOR" == 'nvim' ]]; then
  exec "$EDITOR" -R "@"
else
  exec vim -R "@"
fi