#!/usr/bin/env bash
# Prevents sleep while waiting for a PID to exit using platform tools.
# Usage: waitfor <pid>

set -e
set -u
set -o pipefail

pid="$1"

if hash caffeinate 2>/dev/null; then
  caffeinate -w "$pid"
elif hash systemd-inhibit 2>/dev/null; then
  systemd-inhibit \
    --who=waitfor \
    --why="Awaiting PID $pid" \
    tail --pid="$pid" -f /dev/null
else
  tail --pid="$pid" -f /dev/null
fi